apiVersion: v1
kind: Service
metadata:
  name: {{ include "alliance-auth-helm.fullname" . }}-nginx
  labels:
    {{- include "alliance-auth-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "alliance-auth-helm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alliance-auth-helm.fullname" . }}-auth
  labels:
    {{- include "alliance-auth-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "alliance-auth-helm.selectorLabels" . | nindent 4 }}
